apply plugin: 'com.android.library'

group = 'app.allkept.sharesave'
version = '1.0.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()

android {
  namespace "app.allkept.sharesave"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
  lintOptions { abortOnError false }
}

dependencies {
  implementation "androidx.work:work-runtime-ktx:2.9.1"
}
