// GENERATED by scripts/sync-shared.mjs from packages/contracts/src/index.ts - do not edit here.
// Shared contracts between the mobile app and the Edge Functions. Copied into supabase/functions/_shared by scripts/sync-shared.mjs.
export type { Platform, Kind, NormalizedLink } from "./normalize.ts";
import type { Platform, Kind } from "./normalize.ts";

/** Doors through which saves arrive. */
export type SourceKind = "instagram_dm" | "youtube_playlist";
export type CapturedVia = SourceKind | "share";
export type SourceStatus = "active" | "disconnected" | "unreadable";
export type ItemStatus = "pending" | "ready" | "preview_unavailable" | "no_link" | "failed";
export type ClassificationStatus = "queued" | "processing" | "ready" | "retry_wait" | "failed";
export type ClientOs = "ios" | "android";

export const CATEGORIES = [
  "Food & recipes", "Fitness & health", "Travel & places", "Learning & how-to", "Tech & tools",
  "Money & career", "Design & inspiration", "Style & fashion", "Beauty & self-care", "Home & living",
  "Entertainment", "Humour & memes", "News & opinion", "Life & relationships", "Other",
] as const;
export type Category = (typeof CATEGORIES)[number];

/**
 * What each category means, as the sorting model is told it. A bare list of names left the model
 * to break ties on wording, and like saves scattered; a category without a definition is a type
 * error here, and the prompt test checks every one reaches the model.
 */
export const CATEGORY_GUIDE: Record<Category, string> = {
  "Food & recipes": "cooking, recipes, dishes, restaurants, food reviews.",
  "Fitness & health": "workouts, training, nutrition, sleep, medical and mental-health advice; the body is the subject.",
  "Travel & places": "destinations, trips, hotels, sights; a place is the subject.",
  "Learning & how-to": "teaching whose subject has no category of its own: study skills, languages, science and history explainers, courses.",
  "Tech & tools": "software, apps, AI models and tools, gadgets, coding, workflows built with tools; the tool or technique is the subject.",
  "Money & career": "earning, investing, business and startup stories, jobs, interviews, growing a company or a channel as a business.",
  "Design & inspiration": "visual design, UI/UX, architecture, art, typography, reference and mood boards; the look is the subject.",
  "Style & fashion": "clothes, outfits, accessories, personal style.",
  "Beauty & self-care": "skincare, hair, makeup, grooming.",
  "Home & living": "interiors, furniture, decor, gardening, cleaning, organising, DIY for the home.",
  "Entertainment": "films, series, music, games, sport as spectacle, celebrities, trailers, performances; clips enjoyed for their own sake.",
  "Humour & memes": "the point is the laugh: jokes, skits, memes, pranks.",
  "News & opinion": "current events, politics, commentary.",
  "Life & relationships": "dating, family, friendship, parenting, and personal growth: mindset, motivation, routines, productivity.",
  "Other": "nothing fits, or there is too little to go on.",
};

/** Below this confidence the sorter is guessing: the save is filed under Other and flagged, whatever the guess. */
export const UNSURE_BELOW = 0.4;

export const ENTITY_TYPES = ["place", "product", "recipe", "tool", "person", "brand", "other"] as const;
export type EntityType = (typeof ENTITY_TYPES)[number];

/**
 * The marks an interest may wear: names of filled glyphs in the app's icon font, chosen by the
 * sorting model for each named thing so that IMDb reads as film and a cookbook as a book, rather
 * than every brand wearing the same tag. The first seven are the kinds' own marks, so there is
 * always an honest choice when nothing more specific fits. The app checks each name against the
 * font at compile time; a name that is not a glyph there is a build error, never a blank chip.
 */
export const ENTITY_ICONS = [
  "person-circle", "pricetag", "cube", "navigate", "restaurant", "construct", "sparkles",
  "film", "videocam", "tv", "game-controller", "dice", "musical-notes", "headset", "mic", "radio", "ticket",
  "book", "library", "newspaper", "document-text", "school", "language", "calculator",
  "code-slash", "terminal", "hardware-chip", "server", "cloud", "git-branch", "bug", "hammer", "cut", "layers", "apps",
  "extension-puzzle", "phone-portrait", "laptop", "desktop", "watch", "key", "lock-closed", "shield-checkmark",
  "camera", "image", "color-palette", "brush", "shirt", "glasses", "diamond", "gift",
  "bag-handle", "cart", "storefront", "cash", "card", "wallet", "trending-up", "stats-chart", "business", "briefcase",
  "rocket", "bulb", "chatbubbles", "mail", "calendar", "time",
  "globe", "map", "compass", "airplane", "car", "bicycle", "boat", "train", "bed", "home",
  "leaf", "flower", "paw", "fish", "planet", "telescope", "sunny", "moon", "thunderstorm", "snow", "flame", "water", "umbrella",
  "fast-food", "pizza", "cafe", "wine", "beer", "ice-cream", "nutrition",
  "fitness", "barbell", "football", "basketball", "tennisball", "golf", "baseball", "american-football", "trophy", "walk",
  "body", "heart", "pulse", "medkit", "bandage", "flask",
  "people", "happy", "star", "ribbon", "flag", "balloon",
] as const;
export type EntityIcon = (typeof ENTITY_ICONS)[number];
export const isEntityIcon = (v: unknown): v is EntityIcon => typeof v === "string" && (ENTITY_ICONS as readonly string[]).includes(v);

export const ACTIONABILITY = ["watch", "try", "buy", "go", "read", "reference", "none"] as const;
export type Actionability = (typeof ACTIONABILITY)[number];

/** What makes two captures the same item: the platform's own id when there is one, else the canonical URL. */
export interface ItemIdentity {
  platform: Platform;
  externalId: string | null;
  canonicalUrl: string | null;
}

/** What any door hands to the capture module. */
export interface CaptureInput {
  userId: string;
  sourceId: string | null;
  sourceKind: CapturedVia;
  /** Instagram message id, or YouTube playlist item id. Makes the capture idempotent. */
  sourceEventId: string;
  /** ISO-8601: when the user saved it (message time, playlist add time). */
  savedAt: string;
  sharedUrl?: string;
  sharedText?: string;
  caption?: string;
  /** A temporary media URL to snapshot immediately (Instagram post shares). */
  snapshotUrl?: string;
  /** True when the platform gave no link back to the original (Instagram post shares). */
  noLink?: boolean;
  /** Overrides used when there is no URL to normalise (Instagram post shares): platform, kind and the platform's own id. */
  platform?: Platform;
  kind?: Kind;
  externalId?: string;
  /** Retained independently when a post's permalink supplies the deduplication shortcode. */
  instagramMediaId?: string;
  /** Title when the door knows it (YouTube video title). Captions go in `caption`. */
  title?: string;
}

export interface CaptureResult {
  itemId: string;
  deduplicated: boolean;
  status: ItemStatus;
  platform: Platform;
  kind: Kind;
}

export interface LinkStartResponse {
  code: string;
  expiresAt: string;
}

/** POST /youtube-register (JWT): starts watching a YouTube playlist the person points us at. */
export interface YoutubeRegisterRequest {
  playlistUrl: string;
}

export interface YoutubeRegisterResponse {
  sourceId: string;
  playlistId: string;
  title: string;
  itemCount: number;
  /** True when this playlist was already theirs, so the app can say "still watching" rather than "connected". */
  alreadyConnected: boolean;
}

export interface ItemAiOutput {
  category: Category;
  tags: string[];
  summary: string;
  /** The icon is absent until the sweeper's icon pass has chosen one for the name. */
  entities: { type: EntityType; name: string; icon?: EntityIcon }[];
  language: string;
  actionability: Actionability;
  confidence: number;
  /** Somewhere a person could go to, when the post names one: the place as named, and what places it. Null when there is none. */
  venue: { name: string; locality: string } | null;
  /** A date the post names as something that happens — an event, a launch, a deadline — as ISO 8601. Null when there is none. */
  event_at: string | null;
  /** The words legible in the picture, as written — a sign, a title card, a caption burnt into the frame. Null when there are none. Kept for search and the venue; never shown. */
  screen_text: string | null;
}

export type ApiErrorCode = "bad_request" | "unauthorized" | "not_found" | "conflict" | "rate_limited" | "internal" | "payment_required" | "unavailable" | "unprocessable";

/**
 * Paid in the US, free in India. The first FREE_SAVES saves are free everywhere — a count, not a
 * clock. A store account in a FREE_REGION never reaches the count. The rule itself lives in the
 * database (entitled(), admit_save()); these are the same numbers, for the phone's own copy.
 */
export const FREE_SAVES = 25;
export const FREE_REGIONS = ["IN"] as const;
export interface ApiError {
  error: string;
  code: ApiErrorCode;
}

export const LIMITS = {
  noteMaxChars: 2000,
  textMaxChars: 20000,
  urlMaxChars: 4096,
  linkCodeTtlSeconds: 600,
} as const;

/** Link codes avoid look-alike characters (0/O, 1/I). */
export const LINK_CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
export const LINK_CODE_LENGTH = 6;

/** POST /delete-account (JWT): what was forgotten. */
export interface DeleteAccountResponse { deleted: true; thumbnails: number; events: number; replies: number; items: number; sources: number }

/** POST /reprocess-item (JWT): enrich and classify one item the caller owns, now rather than at the next sweep. */
export interface ReprocessItemRequest { itemId: string; retry?: boolean }
export interface ReprocessItemResponse { status: ItemStatus; category: string | null; classificationStatus?: ClassificationStatus }


/** POST /import-saves (JWT): reads the Instagram export the caller uploaded and creates the saves it names. */
export interface ImportSavesRequest { path: string }
export interface ImportSavesResponse { importId: string; found: number; added: number; skipped: number }

/** public.import_progress(import_id): how far one import has got, counted from the saves themselves. */
export interface ImportProgress { found: number; added: number; ready: number; waiting: number; failed?: number; finished: boolean }

/** Direct share/paste of an Instagram permalink. requestId is reused when retrying a save. */
export interface SaveLinkRequest { text: string; requestId: string }
export type SaveLinkResponse = CaptureResult;

/** What a category holds and what it is about — the Library's header when one category is open. */
export interface CategorySummaryResponse {
  count: number;
  /** Saves by shape, as the library's shape facet names them (vertical, wide, post, link, note…). */
  shapes: Record<string, number>;
  /** Saves by the intent the sorter gave them: try, buy, go, watch, read. */
  intents: Record<string, number>;
  /** The names that keep turning up inside, most first, with the mark the icon pass chose. */
  names: { name: string; kind: string; icon: string | null; n: number }[];
  /** Up to three themes the model wrote; empty when there are too few saves, sorting is off, or nothing could be written. */
  themes: string[];
  /** stored: from an earlier writing; writing: being written now, ask again shortly; none: no themes. */
  freshness: "stored" | "writing" | "none";
  sortingOff?: boolean;
}

/** waitlist: where a sign-up came from. The site sends the two pills; the rest are reserved. */
export type WaitlistSource = "site-hero" | "site-footer" | "site" | "app" | "instagram";
/** waitlist: 200 both ways — a repeat sign-up is not an error to the person typing it. */
export interface WaitlistResponse { joined: boolean; message: string }

// ---------------------------------------------------------------------------------------------
// Weave — an itinerary woven from a person's saves. Understand → select → arrange.
// Spec: internal/superpowers/specs/2026-09-16-weave-itinerary-design.md
// ---------------------------------------------------------------------------------------------

/** What a save is for on a trip, as the understanding stage files it. */
export const WEAVE_KINDS = ["food", "coffee", "nightlife", "culture", "cityscape", "nature", "adventure", "shopping", "stay", "other"] as const;
export type WeaveKind = (typeof WEAVE_KINDS)[number];
export type WeaveGroup = "solo" | "couple" | "family" | "friends";
export type WeavePace = "relaxed" | "full";
export type WeaveTransport = "walk_cab" | "car" | "transit";
export type WeaveBudget = "low" | "mid" | "high";

/** What the saves say, with the saves as evidence — shown to the person and edited before a plan is made. */
export interface WeaveProfile {
  /** Kinds with their share of the trip (shares sum to one) and the save ids that show it. */
  mix: { kind: WeaveKind; share: number; evidence: string[] }[];
  /** Towns with their saves and the nights each deserves, in proportion, at least one; the country as ISO 3166-1 alpha-2, for its holidays. */
  towns: { name: string; country: string | null; saves: number; nights: number }[];
  /** Saves the person clearly means — saved twice, noted, reminded — with the reason. */
  must: { id: string; reason: string }[];
  /** A few words the plan honours: "hidden-gem captions, few landmarks". */
  style: string;
  group: WeaveGroup | null;
  budgetWords: string | null;
  /** Saves that are ads, montages or unclear: they count for nothing. */
  unsure: string[];
}

/** The brief: what the person told us, all of it optional, defaults from the profile. */
export interface WeaveBrief {
  days: number;
  /** YYYY-MM-DD, or null when the dates are not known — then no weekday hours, holidays or season. */
  startDate: string | null;
  nights: { town: string; nights: number }[];
  /** "HH:MM" local on the first and last day, when known. */
  arrival: string | null;
  departure: string | null;
  bases: { town: string; name: string | null }[];
  group: WeaveGroup | null;
  pace: WeavePace;
  transport: WeaveTransport;
  budget: WeaveBudget | null;
  /** Save ids the person insists on, and ones to leave out. */
  must: string[];
  skip: string[];
  note: string | null;
}

export type WeaveSlot = "morning" | "late_morning" | "lunch" | "afternoon" | "evening" | "night";

/** A stop in the plan: a save's id, or "s:<placeId>" for a suggestion not from the saves. */
export interface WeaveStop {
  id: string;
  slot: WeaveSlot;
  /** Why it is here, in the reader's words, citing the saves it rests on. */
  why: string;
  cites: string[];
  /** What the reel said to try, when it did. */
  tip: string | null;
  /** Closed that day, far from the rest, hours unknown, book ahead. */
  warning: string | null;
}

export interface WeaveDay {
  day: number;
  date: string | null;
  town: string;
  theme: string;
  stops: WeaveStop[];
  notes: string | null;
}

export interface WeavePlan {
  overview: string;
  days: WeaveDay[];
  bookAhead: { id: string; what: string; why: string }[];
  /** Saves that were chosen but did not fit, and why — nothing is dropped in silence. */
  leftOut: { id: string; reason: string }[];
  assumptions: string[];
}
