// GENERATED by scripts/sync-shared.mjs from packages/normalize/src/saved-export.ts - do not edit here.
// Reading Instagram's "saved posts" export.
//
// Meta renames fields between exports, so nothing here depends on their key names. It walks the
// whole document, picks up anything that looks like a post link, and takes the nearest timestamp
// and username it can find beside it.

export interface SavedEntry {
  /** The permalink, always normalised to https://www.instagram.com/<kind>/<code>/ */
  url: string;
  /** Post shortcode, which is also the identity we deduplicate on. */
  code: string;
  kind: "p" | "reel" | "tv";
  /** When the person saved it, if the export said. */
  savedAt: string | null;
  /** The account that posted it, if the export said. */
  author: string | null;
}

const LINK = /https?:\/\/(?:www\.)?instagram\.com\/(p|reel|reels|tv)\/([A-Za-z0-9_-]{5,})/i;

/** Seconds or milliseconds since the epoch, as either a number or a numeric string. */
function toIso(value: unknown): string | null {
  const n = typeof value === "number" ? value : typeof value === "string" && /^\d{9,13}$/.test(value) ? Number(value) : NaN;
  if (!Number.isFinite(n) || n <= 0) return null;
  const ms = n > 1e12 ? n : n * 1000;
  const date = new Date(ms);
  if (Number.isNaN(date.getTime())) return null;
  // Instagram has not existed outside this range, so anything else is a coincidence, not a date.
  if (date.getUTCFullYear() < 2010 || date.getTime() > Date.now() + 86_400_000) return null;
  return date.toISOString();
}

const USERNAME = /^[A-Za-z0-9._]{1,30}$/;

/** Timestamps and usernames sitting beside a link, whatever the surrounding keys are called. */
function contextOf(node: Record<string, unknown>): { savedAt: string | null; author: string | null } {
  let savedAt: string | null = null;
  let author: string | null = null;
  const visit = (value: unknown, key: string, depth: number): void => {
    if (depth > 4) return;
    if (typeof value === "object" && value !== null) {
      for (const [k, v] of Object.entries(value as Record<string, unknown>)) visit(v, k, depth + 1);
      return;
    }
    // Meta has used timestamp, creation_timestamp and taken_at across exports; accept the shapes,
    // and let toIso reject anything that is not plausibly a date.
    if (!savedAt && /time|date|taken|saved|_at$|epoch/i.test(key)) savedAt = toIso(value);
    if (!author && typeof value === "string" && /title|user|owner|account/i.test(key) && USERNAME.test(value)) author = value;
  };
  visit(node, "", 0);
  return { savedAt, author };
}

/**
 * Every saved post in an export, newest first, with duplicates removed.
 * Accepts the parsed JSON of saved_posts.json, or of any file that happens to contain such links.
 */
export function parseSavedExport(document: unknown): SavedEntry[] {
  const found = new Map<string, SavedEntry>();

  const walk = (node: unknown, depth: number): void => {
    if (depth > 12 || node === null || node === undefined) return;
    if (Array.isArray(node)) {
      for (const child of node) walk(child, depth + 1);
      return;
    }
    if (typeof node !== "object") return;

    const record = node as Record<string, unknown>;
    const link = findLink(record);
    if (link) {
      const { savedAt, author } = contextOf(record);
      const existing = found.get(link.code);
      if (!existing) found.set(link.code, { ...link, savedAt, author });
      else {
        // Keep whichever copy knows more.
        if (!existing.savedAt && savedAt) existing.savedAt = savedAt;
        if (!existing.author && author) existing.author = author;
      }
    }
    for (const value of Object.values(record)) walk(value, depth + 1);
  };

  walk(document, 0);

  return [...found.values()].sort((a, b) => (b.savedAt ?? "").localeCompare(a.savedAt ?? ""));
}

/** The first post link directly on this object, ignoring links nested deeper. */
function findLink(record: Record<string, unknown>): { url: string; code: string; kind: SavedEntry["kind"] } | null {
  const strings: string[] = [];
  const collect = (value: unknown, depth: number): void => {
    if (depth > 3) return;
    if (typeof value === "string") { strings.push(value); return; }
    if (typeof value === "object" && value !== null) for (const v of Object.values(value as Record<string, unknown>)) collect(v, depth + 1);
  };
  collect(record, 0);

  for (const s of strings) {
    const m = LINK.exec(s);
    if (!m) continue;
    const raw = m[1]!.toLowerCase();
    const kind: SavedEntry["kind"] = raw === "reels" ? "reel" : (raw as SavedEntry["kind"]);
    const code = m[2]!;
    return { url: `https://www.instagram.com/${kind}/${code}/`, code, kind };
  }
  return null;
}
