/**
 * The pictures behind category-marks.ts, one require per file in assets/emoji. Kept apart from the
 * rules so the rules can be tested without a bundler that understands PNG. Generated from the same
 * listing; do not edit by hand.
 */
import type { MarkKey } from "./category-marks";

export const MARK_IMAGES: Record<MarkKey, number> = {
  airplane: require("../assets/emoji/airplane.png"),
  artist_palette: require("../assets/emoji/artist_palette.png"),
  automobile: require("../assets/emoji/automobile.png"),
  balloon: require("../assets/emoji/balloon.png"),
  beach_with_umbrella: require("../assets/emoji/beach_with_umbrella.png"),
  bed: require("../assets/emoji/bed.png"),
  bicycle: require("../assets/emoji/bicycle.png"),
  blossom: require("../assets/emoji/blossom.png"),
  bookmark: require("../assets/emoji/bookmark.png"),
  books: require("../assets/emoji/books.png"),
  briefcase: require("../assets/emoji/briefcase.png"),
  calendar: require("../assets/emoji/calendar.png"),
  camera: require("../assets/emoji/camera.png"),
  cat_face: require("../assets/emoji/cat_face.png"),
  clapper_board: require("../assets/emoji/clapper_board.png"),
  cooking: require("../assets/emoji/cooking.png"),
  dog_face: require("../assets/emoji/dog_face.png"),
  dress: require("../assets/emoji/dress.png"),
  face_with_tears_of_joy: require("../assets/emoji/face_with_tears_of_joy.png"),
  fire: require("../assets/emoji/fire.png"),
  flexed_biceps: require("../assets/emoji/flexed_biceps.png"),
  gem_stone: require("../assets/emoji/gem_stone.png"),
  graduation_cap: require("../assets/emoji/graduation_cap.png"),
  guitar: require("../assets/emoji/guitar.png"),
  hammer_and_wrench: require("../assets/emoji/hammer_and_wrench.png"),
  headphone: require("../assets/emoji/headphone.png"),
  hot_beverage: require("../assets/emoji/hot_beverage.png"),
  house_with_garden: require("../assets/emoji/house_with_garden.png"),
  key: require("../assets/emoji/key.png"),
  label: require("../assets/emoji/label.png"),
  laptop: require("../assets/emoji/laptop.png"),
  leaf_fluttering_in_wind: require("../assets/emoji/leaf_fluttering_in_wind.png"),
  light_bulb: require("../assets/emoji/light_bulb.png"),
  lipstick: require("../assets/emoji/lipstick.png"),
  lotus: require("../assets/emoji/lotus.png"),
  luggage: require("../assets/emoji/luggage.png"),
  microphone: require("../assets/emoji/microphone.png"),
  money_bag: require("../assets/emoji/money_bag.png"),
  musical_note: require("../assets/emoji/musical_note.png"),
  nail_polish: require("../assets/emoji/nail_polish.png"),
  newspaper: require("../assets/emoji/newspaper.png"),
  package: require("../assets/emoji/package.png"),
  paintbrush: require("../assets/emoji/paintbrush.png"),
  party_popper: require("../assets/emoji/party_popper.png"),
  paw_prints: require("../assets/emoji/paw_prints.png"),
  pill: require("../assets/emoji/pill.png"),
  pizza: require("../assets/emoji/pizza.png"),
  popcorn: require("../assets/emoji/popcorn.png"),
  potted_plant: require("../assets/emoji/potted_plant.png"),
  puzzle_piece: require("../assets/emoji/puzzle_piece.png"),
  red_heart: require("../assets/emoji/red_heart.png"),
  ring: require("../assets/emoji/ring.png"),
  robot: require("../assets/emoji/robot.png"),
  rocket: require("../assets/emoji/rocket.png"),
  running_shoe: require("../assets/emoji/running_shoe.png"),
  sailboat: require("../assets/emoji/sailboat.png"),
  shopping_cart: require("../assets/emoji/shopping_cart.png"),
  snowflake: require("../assets/emoji/snowflake.png"),
  soccer_ball: require("../assets/emoji/soccer_ball.png"),
  sparkles: require("../assets/emoji/sparkles.png"),
  speech_balloon: require("../assets/emoji/speech_balloon.png"),
  star: require("../assets/emoji/star.png"),
  sun: require("../assets/emoji/sun.png"),
  television: require("../assets/emoji/television.png"),
  ticket: require("../assets/emoji/ticket.png"),
  trophy: require("../assets/emoji/trophy.png"),
  two_hearts: require("../assets/emoji/two_hearts.png"),
  umbrella: require("../assets/emoji/umbrella.png"),
  video_game: require("../assets/emoji/video_game.png"),
  watch: require("../assets/emoji/watch.png"),
  wine_glass: require("../assets/emoji/wine_glass.png"),
  world_map: require("../assets/emoji/world_map.png"),
  wrapped_gift: require("../assets/emoji/wrapped_gift.png"),
  yellow_heart: require("../assets/emoji/yellow_heart.png"),
};
