// Writes lib/mark-svgs.ts: the picture behind every key in lib/category-marks.ts, taken from the
// free Streamline Plump colour set (CC BY 4.0) as Iconify publishes it. Each "-flat" icon there is
// built from exactly two fills, a dark and a light shade of one blue; they become {ink} and {wash}
// so a mark can be drawn in any category's pair. Run `node scripts/marks.mjs [path-to-json]`; with
// no path the set is fetched. The output is committed; the 1.4 MB source is not.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const SOURCE = "https://raw.githubusercontent.com/iconify/icon-sets/master/json/streamline-plump-color.json";
const DARK = "#2859c5";
const LIGHT = "#8fbffa";

const rules = readFileSync(resolve(here, "../lib/category-marks.ts"), "utf8");
const list = rules.split("export const MARK_KEYS = [")[1]?.split("] as const;")[0];
if (!list) throw new Error("MARK_KEYS not found in lib/category-marks.ts");
const keys = [...list.matchAll(/"([a-z0-9-]+)"/g)].map((m) => m[1]);

const set = process.argv[2]
  ? JSON.parse(readFileSync(process.argv[2], "utf8"))
  : await (await fetch(SOURCE)).json();
if (set.width !== 48 || set.height !== 48) throw new Error(`expected a 48-unit set, got ${set.width}x${set.height}`);

const lines = [];
for (const key of keys) {
  const icon = set.icons[`${key}-flat`];
  if (!icon) throw new Error(`no flat icon named ${key} in the set`);
  const body = icon.body.replaceAll(DARK, "{ink}").replaceAll(LIGHT, "{wash}");
  const stray = body.match(/#[0-9a-fA-F]{6}/);
  if (stray) throw new Error(`${key} carries a third colour, ${stray[0]}; the two-tone rule would not hold`);
  lines.push(`  "${key}": ${JSON.stringify(body)},`);
}

const out = `/**
 * The pictures behind category-marks.ts: Streamline Plump Flat, the free set, CC BY 4.0
 * (https://streamlinehq.com — see assets/marks/LICENSE.md). One SVG body per key, on a 48-unit
 * box, with the set's two blues replaced by {ink} and {wash} so a mark takes its category's pair.
 * Generated by scripts/marks.mjs from the key list in category-marks.ts; do not edit by hand.
 */
import type { MarkKey } from "./category-marks";

export const MARK_SVGS: Record<MarkKey, string> = {
${lines.join("\n")}
};
`;
writeFileSync(resolve(here, "../lib/mark-svgs.ts"), out);
console.log(`wrote lib/mark-svgs.ts: ${keys.length} marks`);
