#!/usr/bin/env node
// Copies shared TypeScript into supabase/functions/_shared. `--check` exits 1 if any copy is stale.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";

const root = resolve(fileURLToPath(new URL("..", import.meta.url)));
const HEADER = (src) => `// GENERATED by scripts/sync-shared.mjs from ${src} - do not edit here.\n`;
const FILES = [
  // Deno needs a real extension on a relative import; Metro needs there to be no misleading one.
  // The source is extensionless, which both TypeScript (Bundler resolution) and Metro accept, and
  // only the Deno copy gets ".ts" added.
  { src: "packages/normalize/src/saved-export.ts", dst: "supabase/functions/_shared/saved-export.ts", rewrite: (s) => s },
  { src: "packages/normalize/src/index.ts", dst: "supabase/functions/_shared/normalize.ts", rewrite: (s) => s.replaceAll('"./saved-export"', '"./saved-export.ts"') },
  { src: "packages/contracts/src/index.ts", dst: "supabase/functions/_shared/contracts.ts", rewrite: (s) => s.replaceAll('"@allkept/normalize"', '"./normalize.ts"') },
];

const check = process.argv.includes("--check");
let stale = 0;
mkdirSync(resolve(root, "supabase/functions/_shared"), { recursive: true });
for (const f of FILES) {
  const expected = HEADER(f.src) + f.rewrite(readFileSync(resolve(root, f.src), "utf8"));
  const dstPath = resolve(root, f.dst);
  const current = existsSync(dstPath) ? readFileSync(dstPath, "utf8") : null;
  if (current === expected) continue;
  if (check) { console.error(`stale: ${f.dst}`); stale++; continue; }
  writeFileSync(dstPath, expected);
  console.log(`synced ${f.dst}`);
}
if (check && stale > 0) process.exit(1);
